# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true

- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '*.xcworkspace'
    scheme: 'sampleapp-ios-swift'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_11.3.app'
    packageApp: false
    publishJUnitResults: true
  
- task: CopyFiles@2
  inputs:
    contents: '**/*.app'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'outputs'
    artifactType: 'container'

    
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'KevinApps/AppCenterDemo-iOS'
    appFile: '$(System.DefaultWorkingDirectory)/*.app'
    releaseNotesOption: 'input'
    releaseNotesInput: 'test'
    destinationType: 'groups'
    distributionGroupId: 'e6f20ff1-c27e-41f1-aa84-ef4d2d9078e3'